import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt({
  // `apphost/` and `desktop/` are separate packages, each with its own ESLint
  // config and its own lint script. Most of `apphost/` is generated by Aspire
  // anyway, and `desktop/` must stay out of the root install entirely —
  // `electron` is a several-hundred-megabyte dependency and the root install
  // is what the Dockerfile runs.
  ignores: ['worker/**', 'apphost/**', 'desktop/**', 'data/**', '.scratch/**'],
})
