import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt({
  // `apphost/`, `desktop/`, and `site/` are separate packages, each installed
  // from inside its own directory. Most of `apphost/` is generated by Aspire
  // anyway, and `desktop/` must stay out of the root install entirely —
  // `electron` is a several-hundred-megabyte dependency and the root install
  // is what the Dockerfile runs. `site/` is the Website, built by Vercel, with
  // no lint of its own: `site/src/lib/` holds the one plain module with logic
  // in it, tested from `tests/unit/site/`, so it is linted from here too.
  ignores: [
    'worker/**', 'apphost/**', 'desktop/**', 'data/**', '.scratch/**',
    'site/*', '!site/src/', 'site/src/*', '!site/src/lib/',
  ],
})
