import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt({
  // `apphost/` is a separate package with its own ESLint config and its own
  // lint script; most of it is generated by Aspire anyway.
  ignores: ['worker/**', 'apphost/**', 'data/**', '.scratch/**'],
})
